"""
Canonical bootstrap defaults shared between the legacy runtime and CLI.

This module keeps reproducible fallback values in one place so that both
`wgp` and CLI entry points stay aligned when flags or defaults evolve.
"""

from __future__ import annotations

from typing import Any, Dict


GENERATION_FALLBACKS: Dict[str, Any] = {
    "image_mode": 0,
    "prompt": "",
    "negative_prompt": "",
    "resolution": "832x480",
    "video_length": 81,
    "batch_size": 1,
    "seed": -1,
    "force_fps": "",
    "num_inference_steps": 30,
    "guidance_scale": 5.0,
    "guidance2_scale": 5.0,
    "guidance3_scale": 5.0,
    "switch_threshold": 0,
    "switch_threshold2": 0,
    "guidance_phases": 1,
    "model_switch_phase": 1,
    "audio_guidance_scale": 4.0,
    "flow_shift": 5.0,
    "sample_solver": "unipc",
    "embedded_guidance_scale": 6.0,
    "repeat_generation": 1,
    "multi_prompts_gen_type": 0,
    "multi_images_gen_type": 0,
    "skip_steps_cache_type": "",
    "skip_steps_multiplier": 1.5,
    "skip_steps_start_step_perc": 20,
    "tea_cache_setting": 0,
    "tea_cache_start_step_perc": 20,
    "activated_loras": [],
    "loras_multipliers": "",
    "image_prompt_type": "",
    "image_start": None,
    "image_end": None,
    "model_mode": None,
    "video_source": None,
    "keep_frames_video_source": "",
    "video_prompt_type": "",
    "image_refs": None,
    "frames_positions": "",
    "video_guide": None,
    "image_guide": None,
    "keep_frames_video_guide": "",
    "denoising_strength": 1.0,
    "video_guide_outpainting": "",
    "video_mask": None,
    "image_mask": None,
    "control_net_weight": 1.0,
    "control_net_weight2": 1.0,
    "control_net_weight_alt": 1.0,
    "mask_expand": 0,
    "audio_guide": None,
    "audio_guide2": None,
    "audio_source": None,
    "audio_prompt_type": "",
    "speakers_locations": "",
    "sliding_window_size": 129,
    "sliding_window_overlap": 17,
    "sliding_window_color_correction_strength": 0.0,
    "sliding_window_overlap_noise": 0,
    "sliding_window_discard_last_frames": 0,
    "image_refs_relative_size": 50,
    "remove_background_images_ref": 0,
    "temporal_upsampling": "",
    "spatial_upsampling": "",
    "film_grain_intensity": 0.0,
    "film_grain_saturation": 0.5,
    "MMAudio_setting": 0,
    "MMAudio_prompt": "",
    "MMAudio_neg_prompt": "",
    "RIFLEx_setting": 0,
    "NAG_scale": 1.0,
    "NAG_tau": 3.5,
    "NAG_alpha": 0.5,
    "slg_switch": 0,
    "slg_layers": [9],
    "slg_start_perc": 10,
    "slg_end_perc": 90,
    "apg_switch": 0,
    "cfg_star_switch": 0,
    "cfg_zero_step": -1,
    "prompt_enhancer": "",
    "min_frames_if_references": 1,
    "override_profile": -1,
    "pace": 0.5,
    "exaggeration": 0.5,
    "temperature": 0.8,
    "mode": "",
}


DEFAULT_BOOTSTRAP_VALUES: Dict[str, Any] = {
    "advanced": False,
    "attention": "",
    "bf16": False,
    "check_loras": False,
    "compile": False,
    "frames": 0,
    "fp16": False,
    "gpu": "",
    "i2v": False,
    "i2v_14B": False,
    "i2v_1_3B": False,
    "lora_dir": "",
    "lora_dir_flux": "loras_flux",
    "lora_dir_i2v": "",
    "lora_dir_ltxv": "loras_ltxv",
    "lora_dir_qwen": "loras_qwen",
    "lora_dir_tts": "loras_tts",
    "lora_preset": "",
    "perc_reserved_mem_max": 0.0,
    "preload": 0,
    "profile": -1,
    "save_masks": False,
    "save_quantized": False,
    "save_speakers": False,
    "seed": GENERATION_FALLBACKS["seed"],
    "settings": "settings",
    "steps": 0,
    "t2v": False,
    "t2v_14B": False,
    "t2v_1_3B": False,
    "vace_1_3B": False,
    "vae_config": "",
    "verbose": 1,
    "vram_safety_coefficient": 0.8,
}
